import { dateFromToday } from "./format";
import type { Company, DB, DocumentRec, OcrResult } from "./types";

// ============================================================
// デモ用サンプルデータ
// 日付はすべて「今日」からの相対で生成するため、いつ開いても
// ダッシュボードに今月の数字・期限超過・警告が表示される
// ============================================================

/** 相対日付ヘルパー */
const d = dateFromToday;

/** 相対タイムスタンプ（createdAt/updatedAt用） */
function ts(offsetDays: number): string {
  return new Date(Date.now() + offsetDays * 86400000).toISOString();
}

export function emptyCompany(): Company {
  return {
    id: "company-1",
    name: "",
    postalCode: "",
    address: "",
    phone: "",
    email: "",
    invoiceRegistrationNumber: "",
    bankName: "",
    bankBranch: "",
    bankAccountType: "普通",
    bankAccountNumber: "",
    bankAccountHolder: "",
    logoUrl: null,
  };
}

export function emptyDB(): DB {
  return {
    company: emptyCompany(),
    members: [],
    projects: [],
    revenues: [],
    costs: [],
    documents: [],
    estimates: [],
    invoices: [],
    hydrated: false,
  };
}

function ocr(partial: Partial<OcrResult> & Pick<OcrResult, "documentType" | "vendorName" | "documentDate" | "totalAmount" | "taxAmount" | "confidence">): OcrResult {
  return { items: [], ...partial };
}

export function seedDemoData(): DB {
  const db: DB = {
    hydrated: true,
    company: {
      id: "company-1",
      name: "デモ工務店株式会社",
      postalCode: "171-0021",
      address: "東京都豊島区西池袋1-2-3 サンシャインビル4F",
      phone: "03-1234-5678",
      email: "info@demo-koumuten.example.jp",
      invoiceRegistrationNumber: "T1234567890123",
      bankName: "三井住友銀行",
      bankBranch: "池袋支店",
      bankAccountType: "普通",
      bankAccountNumber: "1234567",
      bankAccountHolder: "デモコウムテン（カ",
      logoUrl: null,
    },
    members: [
      { id: "m1", name: "山田 太郎", email: "yamada@demo.example.jp", role: "owner", createdAt: ts(-365) },
      { id: "m2", name: "佐藤 健一", email: "sato@demo.example.jp", role: "admin", createdAt: ts(-300) },
      { id: "m3", name: "鈴木 大輔", email: "suzuki@demo.example.jp", role: "staff", createdAt: ts(-200) },
      { id: "m4", name: "田中 美咲", email: "tanaka@demo.example.jp", role: "viewer", createdAt: ts(-150) },
    ],
    projects: [
      {
        id: "p1",
        name: "A様邸 キッチンリフォーム",
        customerName: "阿部 誠",
        siteAddress: "東京都練馬区豊玉北2-8-15",
        managerId: "m2",
        status: "invoiced",
        startDate: d(-45),
        dueDate: d(-5),
        completedDate: d(-7),
        memo: "完工済み。完工金の入金待ち。追加のコンロ変更分は完工金に含む。",
        tags: ["リフォーム", "戸建"],
        color: "#F97316",
        createdAt: ts(-50),
        updatedAt: ts(-3),
      },
      {
        id: "p2",
        name: "B店舗 原状回復工事",
        customerName: "株式会社ベルフーズ",
        siteAddress: "東京都新宿区高田馬場3-12-8 1F",
        managerId: "m2",
        status: "completed",
        startDate: d(-20),
        dueDate: d(-2),
        completedDate: d(-1),
        memo: "引き渡し完了。請求書を今週中に発行すること。",
        tags: ["店舗", "原状回復"],
        color: "#3B82F6",
        createdAt: ts(-25),
        updatedAt: ts(-1),
      },
      {
        id: "p3",
        name: "Cアパート 外壁補修工事",
        customerName: "大和不動産管理株式会社",
        siteAddress: "埼玉県川口市芝新町5-22",
        managerId: "m3",
        status: "in_progress",
        startDate: d(-15),
        dueDate: d(20),
        completedDate: null,
        memo: "着手金入金済み。天候により工期が延びる可能性あり。",
        tags: ["外装", "集合住宅"],
        color: "#06B6D4",
        createdAt: ts(-18),
        updatedAt: ts(-1),
      },
      {
        id: "p4",
        name: "D様邸 給湯器交換",
        customerName: "出口 幸子",
        siteAddress: "東京都板橋区成増4-6-2",
        managerId: "m3",
        status: "invoiced",
        startDate: d(-12),
        dueDate: d(-10),
        completedDate: d(-10),
        memo: "支払期限を過ぎているため要フォロー。電話連絡すること。",
        tags: ["設備", "小工事"],
        color: "#10B981",
        createdAt: ts(-13),
        updatedAt: ts(-2),
      },
      {
        id: "p5",
        name: "E社 オフィス内装工事",
        customerName: "株式会社エムズプランニング",
        siteAddress: "東京都渋谷区恵比寿1-19-10 6F",
        managerId: "m2",
        status: "in_progress",
        startDate: d(-30),
        dueDate: d(10),
        completedDate: null,
        memo: "追加造作分が原価超過の原因。追加見積を提出し請求交渉中。",
        tags: ["オフィス", "内装"],
        color: "#8B5CF6",
        createdAt: ts(-35),
        updatedAt: ts(0),
      },
      {
        id: "p6",
        name: "F様邸 トイレ改修工事",
        customerName: "藤本 隆",
        siteAddress: "東京都杉並区阿佐谷南1-14-7",
        managerId: "m3",
        status: "paid",
        startDate: d(-75),
        dueDate: d(-65),
        completedDate: d(-64),
        memo: "入金確認済み。完了。",
        tags: ["設備", "小工事"],
        color: "#F59E0B",
        createdAt: ts(-80),
        updatedAt: ts(-55),
      },
      {
        id: "p7",
        name: "H様邸 クロス張替え",
        customerName: "原田 恵子",
        siteAddress: "東京都中野区鷺宮2-3-11",
        managerId: "m2",
        status: "paid",
        startDate: d(-130),
        dueDate: d(-121),
        completedDate: d(-120),
        memo: "",
        tags: ["内装"],
        color: "#F43F5E",
        createdAt: ts(-135),
        updatedAt: ts(-110),
      },
      {
        id: "p8",
        name: "G様邸 浴室リフォーム",
        customerName: "五十嵐 純",
        siteAddress: "東京都北区赤羽西3-9-4",
        managerId: "m2",
        status: "estimate",
        startDate: d(14),
        dueDate: d(30),
        completedDate: null,
        memo: "見積提出済み。奥様が費用面を検討中。今週末に返事予定。",
        tags: ["リフォーム", "戸建"],
        color: "#64748B",
        createdAt: ts(-8),
        updatedAt: ts(-5),
      },
      {
        id: "p9",
        name: "I社 倉庫改修工事",
        customerName: "株式会社イワタ物流",
        siteAddress: "埼玉県戸田市美女木東1-3",
        managerId: "m1",
        status: "lost",
        startDate: null,
        dueDate: null,
        completedDate: null,
        memo: "相見積の結果、価格面で他社に決定。次回案件で再提案予定。",
        tags: ["倉庫"],
        color: "#64748B",
        createdAt: ts(-45),
        updatedAt: ts(-15),
      },
    ],
    revenues: [
      // p1: A様邸 キッチンリフォーム（売上 2,800,000）
      {
        id: "r1", projectId: "p1", title: "契約金（着手金）",
        amount: 1500000, taxType: "inclusive", taxAmount: 136364,
        billingDueDate: d(-42), billedDate: d(-40), paymentDueDate: d(-25), paidDate: d(-35),
        status: "paid", memo: "", documentId: null, createdAt: ts(-42), updatedAt: ts(-35),
      },
      {
        id: "r2", projectId: "p1", title: "完工金",
        amount: 1300000, taxType: "inclusive", taxAmount: 118182,
        billingDueDate: d(-5), billedDate: d(-3), paymentDueDate: d(25), paidDate: null,
        status: "billed", memo: "追加コンロ変更分を含む", documentId: null, createdAt: ts(-5), updatedAt: ts(-3),
      },
      // p2: B店舗 原状回復（売上 1,650,000 未請求）
      {
        id: "r3", projectId: "p2", title: "原状回復工事一式",
        amount: 1650000, taxType: "inclusive", taxAmount: 150000,
        billingDueDate: d(4), billedDate: null, paymentDueDate: null, paidDate: null,
        status: "unbilled", memo: "引き渡し完了済み。早急に請求書発行", documentId: null, createdAt: ts(-10), updatedAt: ts(-1),
      },
      // p3: Cアパート 外壁補修（売上 3,200,000）
      {
        id: "r4", projectId: "p3", title: "着手金（50%）",
        amount: 1600000, taxType: "inclusive", taxAmount: 145455,
        billingDueDate: d(-15), billedDate: d(-14), paymentDueDate: d(-5), paidDate: d(-8),
        status: "paid", memo: "", documentId: null, createdAt: ts(-15), updatedAt: ts(-8),
      },
      {
        id: "r5", projectId: "p3", title: "完工金（50%）",
        amount: 1600000, taxType: "inclusive", taxAmount: 145455,
        billingDueDate: d(22), billedDate: null, paymentDueDate: null, paidDate: null,
        status: "unbilled", memo: "完工後に請求", documentId: null, createdAt: ts(-15), updatedAt: ts(-15),
      },
      // p4: D様邸 給湯器交換（売上 380,000 入金遅延）
      {
        id: "r6", projectId: "p4", title: "給湯器交換工事",
        amount: 380000, taxType: "inclusive", taxAmount: 34545,
        billingDueDate: d(-10), billedDate: d(-9), paymentDueDate: d(-2), paidDate: null,
        status: "billed", memo: "支払期限超過。要フォロー", documentId: null, createdAt: ts(-10), updatedAt: ts(-2),
      },
      // p5: E社 オフィス内装（売上 4,500,000）
      {
        id: "r7", projectId: "p5", title: "着手金",
        amount: 2000000, taxType: "inclusive", taxAmount: 181818,
        billingDueDate: d(-26), billedDate: d(-25), paymentDueDate: d(-10), paidDate: d(-18),
        status: "paid", memo: "", documentId: null, createdAt: ts(-26), updatedAt: ts(-18),
      },
      {
        id: "r8", projectId: "p5", title: "残金",
        amount: 2500000, taxType: "inclusive", taxAmount: 227273,
        billingDueDate: d(12), billedDate: null, paymentDueDate: null, paidDate: null,
        status: "unbilled", memo: "追加工事分の扱いを協議中", documentId: null, createdAt: ts(-26), updatedAt: ts(-2),
      },
      // p6: F様邸 トイレ改修（売上 450,000 入金済）
      {
        id: "r9", projectId: "p6", title: "トイレ改修工事一式",
        amount: 450000, taxType: "inclusive", taxAmount: 40909,
        billingDueDate: d(-62), billedDate: d(-60), paymentDueDate: d(-45), paidDate: d(-55),
        status: "paid", memo: "", documentId: null, createdAt: ts(-62), updatedAt: ts(-55),
      },
      // p7: H様邸 クロス張替え（売上 280,000 入金済）
      {
        id: "r10", projectId: "p7", title: "クロス張替え工事",
        amount: 280000, taxType: "inclusive", taxAmount: 25455,
        billingDueDate: d(-119), billedDate: d(-118), paymentDueDate: d(-100), paidDate: d(-110),
        status: "paid", memo: "", documentId: null, createdAt: ts(-119), updatedAt: ts(-110),
      },
    ],
    costs: [
      // ---------- p1: A様邸（原価 1,725,000 / 発注1,200,000 材料480,000 経費45,000）----------
      {
        id: "c1", projectId: "p1", type: "order", vendorName: "佐藤設備工業",
        title: "水道・ガス配管工事一式", category: null,
        amount: 850000, taxType: "inclusive", taxAmount: 77273,
        paymentMethod: "transfer", purchaseDate: d(-30), paymentDueDate: d(-10), paidDate: d(-10),
        status: "paid", memo: "", documentId: "d2", createdAt: ts(-30), updatedAt: ts(-10),
      },
      {
        id: "c2", projectId: "p1", type: "order", vendorName: "山川電気",
        title: "キッチン電気配線工事", category: null,
        amount: 350000, taxType: "inclusive", taxAmount: 31818,
        paymentMethod: "invoice", purchaseDate: d(-20), paymentDueDate: d(24), paidDate: null,
        status: "unpaid", memo: "月末締め翌月末払い", documentId: null, createdAt: ts(-20), updatedAt: ts(-20),
      },
      {
        id: "c3", projectId: "p1", type: "material", vendorName: "コーナンPRO 練馬店",
        title: "木材・下地材ほか", category: null,
        amount: 68000, taxType: "inclusive", taxAmount: 6182,
        paymentMethod: "cash", purchaseDate: d(-32), paymentDueDate: null, paidDate: d(-32),
        status: "paid", memo: "", documentId: "d1", createdAt: ts(-32), updatedAt: ts(-32),
      },
      {
        id: "c4", projectId: "p1", type: "material", vendorName: "クリナップ",
        title: "システムキッチン本体・パネル", category: null,
        amount: 380000, taxType: "inclusive", taxAmount: 34545,
        paymentMethod: "transfer", purchaseDate: d(-35), paymentDueDate: d(-15), paidDate: d(-15),
        status: "paid", memo: "", documentId: null, createdAt: ts(-35), updatedAt: ts(-15),
      },
      {
        id: "c5", projectId: "p1", type: "material", vendorName: "カインズ 練馬店",
        title: "内装補修材・コーキング", category: null,
        amount: 32000, taxType: "inclusive", taxAmount: 2909,
        paymentMethod: "credit", purchaseDate: d(-18), paymentDueDate: null, paidDate: d(-18),
        status: "paid", memo: "", documentId: null, createdAt: ts(-18), updatedAt: ts(-18),
      },
      {
        id: "c6", projectId: "p1", type: "expense", vendorName: "タイムズ練馬豊玉",
        title: "現場前コインパーキング", category: "parking",
        amount: 12000, taxType: "inclusive", taxAmount: 1091,
        paymentMethod: "cash", purchaseDate: d(-14), paymentDueDate: null, paidDate: d(-14),
        status: "paid", memo: "工事期間中の駐車場代まとめ", documentId: null, createdAt: ts(-14), updatedAt: ts(-14),
      },
      {
        id: "c7", projectId: "p1", type: "expense", vendorName: "エコ産業",
        title: "解体材処分費", category: "disposal",
        amount: 33000, taxType: "inclusive", taxAmount: 3000,
        paymentMethod: "cash", purchaseDate: d(-28), paymentDueDate: null, paidDate: d(-28),
        status: "paid", memo: "", documentId: null, createdAt: ts(-28), updatedAt: ts(-28),
      },

      // ---------- p2: B店舗（原価 1,405,000 / 発注700,000 材料520,000 経費185,000）----------
      {
        id: "c8", projectId: "p2", type: "order", vendorName: "内装工房ナカムラ",
        title: "クロス・床仕上げ工事", category: null,
        amount: 700000, taxType: "inclusive", taxAmount: 63636,
        paymentMethod: "invoice", purchaseDate: d(-8), paymentDueDate: d(20), paidDate: null,
        status: "unpaid", memo: "", documentId: "d5", createdAt: ts(-8), updatedAt: ts(-3),
      },
      {
        id: "c9", projectId: "p2", type: "material", vendorName: "サンゲツ",
        title: "クロス材・床材", category: null,
        amount: 285000, taxType: "inclusive", taxAmount: 25909,
        paymentMethod: "transfer", purchaseDate: d(-16), paymentDueDate: d(-2), paidDate: d(-2),
        status: "paid", memo: "", documentId: null, createdAt: ts(-16), updatedAt: ts(-2),
      },
      {
        id: "c10", projectId: "p2", type: "material", vendorName: "建デポ 新宿店",
        title: "ボード・パテ・副資材", category: null,
        amount: 155000, taxType: "inclusive", taxAmount: 14091,
        paymentMethod: "credit", purchaseDate: d(-14), paymentDueDate: null, paidDate: d(-14),
        status: "paid", memo: "", documentId: null, createdAt: ts(-14), updatedAt: ts(-14),
      },
      {
        id: "c11", projectId: "p2", type: "material", vendorName: "コーナンPRO 中野店",
        title: "金物・消耗品", category: null,
        amount: 80000, taxType: "inclusive", taxAmount: 7273,
        paymentMethod: "cash", purchaseDate: d(-10), paymentDueDate: null, paidDate: d(-10),
        status: "paid", memo: "", documentId: null, createdAt: ts(-10), updatedAt: ts(-10),
      },
      {
        id: "c12", projectId: "p2", type: "expense", vendorName: "エコ産業",
        title: "内装廃材処分費", category: "disposal",
        amount: 145000, taxType: "inclusive", taxAmount: 13182,
        paymentMethod: "invoice", purchaseDate: d(-2), paymentDueDate: d(28), paidDate: null,
        status: "unpaid", memo: "", documentId: "d8", createdAt: ts(-2), updatedAt: ts(-1),
      },
      {
        id: "c13", projectId: "p2", type: "expense", vendorName: "ENEOS",
        title: "ガソリン代", category: "fuel",
        amount: 18000, taxType: "inclusive", taxAmount: 1636,
        paymentMethod: "credit", purchaseDate: d(-9), paymentDueDate: null, paidDate: d(-9),
        status: "paid", memo: "", documentId: null, createdAt: ts(-9), updatedAt: ts(-9),
      },
      {
        id: "c14", projectId: "p2", type: "expense", vendorName: "タイムズ高田馬場",
        title: "駐車場代", category: "parking",
        amount: 22000, taxType: "inclusive", taxAmount: 2000,
        paymentMethod: "cash", purchaseDate: d(-4), paymentDueDate: null, paidDate: d(-4),
        status: "paid", memo: "", documentId: null, createdAt: ts(-4), updatedAt: ts(-4),
      },

      // ---------- p3: Cアパート（原価 2,165,000 / 発注1,350,000 材料720,000 経費95,000）----------
      {
        id: "c15", projectId: "p3", type: "order", vendorName: "東京足場サービス",
        title: "足場架設・解体", category: null,
        amount: 550000, taxType: "inclusive", taxAmount: 50000,
        paymentMethod: "transfer", purchaseDate: d(-13), paymentDueDate: d(-1), paidDate: d(-1),
        status: "paid", memo: "", documentId: null, createdAt: ts(-13), updatedAt: ts(-1),
      },
      {
        id: "c16", projectId: "p3", type: "order", vendorName: "塗装テクノ",
        title: "外壁塗装工事（手間）", category: null,
        amount: 800000, taxType: "inclusive", taxAmount: 72727,
        paymentMethod: "invoice", purchaseDate: d(-5), paymentDueDate: d(30), paidDate: null,
        status: "unpaid", memo: "", documentId: null, createdAt: ts(-5), updatedAt: ts(-5),
      },
      {
        id: "c17", projectId: "p3", type: "material", vendorName: "エスケー化研",
        title: "塗料・シーリング材", category: null,
        amount: 480000, taxType: "inclusive", taxAmount: 43636,
        paymentMethod: "transfer", purchaseDate: d(-11), paymentDueDate: d(-1), paidDate: d(-1),
        status: "paid", memo: "", documentId: null, createdAt: ts(-11), updatedAt: ts(-1),
      },
      {
        id: "c18", projectId: "p3", type: "material", vendorName: "建デポ 川口店",
        title: "補修モルタル・下地材", category: null,
        amount: 240000, taxType: "inclusive", taxAmount: 21818,
        paymentMethod: "invoice", purchaseDate: d(-3), paymentDueDate: d(15), paidDate: null,
        status: "unpaid", memo: "", documentId: null, createdAt: ts(-3), updatedAt: ts(-3),
      },
      {
        id: "c19", projectId: "p3", type: "expense", vendorName: "首都高速",
        title: "ETC利用料（現場往復）", category: "highway",
        amount: 3200, taxType: "inclusive", taxAmount: 291,
        paymentMethod: "credit", purchaseDate: d(-2), paymentDueDate: null, paidDate: d(-2),
        status: "paid", memo: "", documentId: "d7", createdAt: ts(-2), updatedAt: ts(-2),
      },
      {
        id: "c20", projectId: "p3", type: "expense", vendorName: "ENEOS",
        title: "ガソリン代", category: "fuel",
        amount: 24000, taxType: "inclusive", taxAmount: 2182,
        paymentMethod: "credit", purchaseDate: d(-6), paymentDueDate: null, paidDate: d(-6),
        status: "paid", memo: "", documentId: null, createdAt: ts(-6), updatedAt: ts(-6),
      },
      {
        id: "c21", projectId: "p3", type: "expense", vendorName: "現場雑費",
        title: "養生材・ウエス等", category: "site_misc",
        amount: 43000, taxType: "inclusive", taxAmount: 3909,
        paymentMethod: "cash", purchaseDate: d(-7), paymentDueDate: null, paidDate: d(-7),
        status: "paid", memo: "", documentId: null, createdAt: ts(-7), updatedAt: ts(-7),
      },
      {
        id: "c22", projectId: "p3", type: "expense", vendorName: "タイムズ川口芝",
        title: "駐車場代", category: "parking",
        amount: 24800, taxType: "inclusive", taxAmount: 2255,
        paymentMethod: "cash", purchaseDate: d(-1), paymentDueDate: null, paidDate: d(-1),
        status: "paid", memo: "", documentId: null, createdAt: ts(-1), updatedAt: ts(-1),
      },

      // ---------- p4: D様邸（原価 310,000 / 材料302,000 経費8,000）----------
      {
        id: "c23", projectId: "p4", type: "material", vendorName: "ノーリツ",
        title: "給湯器本体（24号オート）", category: null,
        amount: 272000, taxType: "inclusive", taxAmount: 24727,
        paymentMethod: "transfer", purchaseDate: d(-12), paymentDueDate: d(-5), paidDate: d(-5),
        status: "paid", memo: "", documentId: null, createdAt: ts(-12), updatedAt: ts(-5),
      },
      {
        id: "c24", projectId: "p4", type: "material", vendorName: "コーナンPRO 板橋店",
        title: "配管部材・保温材", category: null,
        amount: 30000, taxType: "inclusive", taxAmount: 2727,
        paymentMethod: "cash", purchaseDate: d(-11), paymentDueDate: null, paidDate: d(-11),
        status: "paid", memo: "", documentId: null, createdAt: ts(-11), updatedAt: ts(-11),
      },
      {
        id: "c25", projectId: "p4", type: "expense", vendorName: "タイムズ成増",
        title: "駐車場代", category: "parking",
        amount: 8000, taxType: "inclusive", taxAmount: 727,
        paymentMethod: "cash", purchaseDate: d(-10), paymentDueDate: null, paidDate: d(-10),
        status: "paid", memo: "", documentId: null, createdAt: ts(-10), updatedAt: ts(-10),
      },

      // ---------- p5: E社 オフィス内装（原価 4,730,000 → 赤字案件）----------
      {
        id: "c26", projectId: "p5", type: "order", vendorName: "パーティション東京",
        title: "間仕切り工事", category: null,
        amount: 1250000, taxType: "inclusive", taxAmount: 113636,
        paymentMethod: "transfer", purchaseDate: d(-22), paymentDueDate: d(-8), paidDate: d(-8),
        status: "paid", memo: "", documentId: null, createdAt: ts(-22), updatedAt: ts(-8),
      },
      {
        id: "c27", projectId: "p5", type: "order", vendorName: "電設工業",
        title: "電気・LAN配線工事", category: null,
        amount: 950000, taxType: "inclusive", taxAmount: 86364,
        paymentMethod: "invoice", purchaseDate: d(-10), paymentDueDate: d(18), paidDate: null,
        status: "unpaid", memo: "", documentId: null, createdAt: ts(-10), updatedAt: ts(-10),
      },
      {
        id: "c28", projectId: "p5", type: "order", vendorName: "内装工房ナカムラ",
        title: "床・クロス工事", category: null,
        amount: 700000, taxType: "inclusive", taxAmount: 63636,
        paymentMethod: "invoice", purchaseDate: d(-4), paymentDueDate: d(25), paidDate: null,
        status: "unpaid", memo: "", documentId: null, createdAt: ts(-4), updatedAt: ts(-4),
      },
      {
        id: "c29", projectId: "p5", type: "material", vendorName: "オカムラ",
        title: "オフィス家具・造作材", category: null,
        amount: 680000, taxType: "inclusive", taxAmount: 61818,
        paymentMethod: "transfer", purchaseDate: d(-15), paymentDueDate: d(-2), paidDate: d(-2),
        status: "paid", memo: "", documentId: null, createdAt: ts(-15), updatedAt: ts(-2),
      },
      {
        id: "c30", projectId: "p5", type: "material", vendorName: "建デポ 渋谷店",
        title: "LGS・ボード・建材", category: null,
        amount: 470000, taxType: "inclusive", taxAmount: 42727,
        paymentMethod: "credit", purchaseDate: d(-19), paymentDueDate: null, paidDate: d(-19),
        status: "paid", memo: "", documentId: null, createdAt: ts(-19), updatedAt: ts(-19),
      },
      {
        id: "c31", projectId: "p5", type: "material", vendorName: "大光電機",
        title: "照明器具", category: null,
        amount: 300000, taxType: "inclusive", taxAmount: 27273,
        paymentMethod: "invoice", purchaseDate: d(-2), paymentDueDate: d(26), paidDate: null,
        status: "unpaid", memo: "追加発注分", documentId: null, createdAt: ts(-2), updatedAt: ts(-2),
      },
      {
        id: "c32", projectId: "p5", type: "expense", vendorName: "エコ産業",
        title: "内装廃材処分費", category: "disposal",
        amount: 180000, taxType: "inclusive", taxAmount: 16364,
        paymentMethod: "invoice", purchaseDate: d(-6), paymentDueDate: d(22), paidDate: null,
        status: "unpaid", memo: "", documentId: null, createdAt: ts(-6), updatedAt: ts(-6),
      },
      {
        id: "c33", projectId: "p5", type: "expense", vendorName: "現場雑費",
        title: "養生・清掃・雑材", category: "site_misc",
        amount: 95000, taxType: "inclusive", taxAmount: 8636,
        paymentMethod: "cash", purchaseDate: d(-8), paymentDueDate: null, paidDate: d(-8),
        status: "paid", memo: "", documentId: null, createdAt: ts(-8), updatedAt: ts(-8),
      },
      {
        id: "c34", projectId: "p5", type: "expense", vendorName: "首都高速",
        title: "高速代（資材運搬）", category: "highway",
        amount: 45000, taxType: "inclusive", taxAmount: 4091,
        paymentMethod: "credit", purchaseDate: d(-12), paymentDueDate: null, paidDate: d(-12),
        status: "paid", memo: "", documentId: null, createdAt: ts(-12), updatedAt: ts(-12),
      },
      {
        id: "c35", projectId: "p5", type: "expense", vendorName: "JR東日本",
        title: "職人交通費", category: "travel",
        amount: 60000, taxType: "none", taxAmount: 0,
        paymentMethod: "cash", purchaseDate: d(-5), paymentDueDate: null, paidDate: d(-5),
        status: "paid", memo: "", documentId: null, createdAt: ts(-5), updatedAt: ts(-5),
      },

      // ---------- p6: F様邸 トイレ改修（原価 310,000）----------
      {
        id: "c36", projectId: "p6", type: "material", vendorName: "TOTO",
        title: "便器・ウォシュレット", category: null,
        amount: 195000, taxType: "inclusive", taxAmount: 17727,
        paymentMethod: "transfer", purchaseDate: d(-72), paymentDueDate: d(-60), paidDate: d(-60),
        status: "paid", memo: "", documentId: null, createdAt: ts(-72), updatedAt: ts(-60),
      },
      {
        id: "c37", projectId: "p6", type: "material", vendorName: "サンゲツ",
        title: "クッションフロア・クロス", category: null,
        amount: 85000, taxType: "inclusive", taxAmount: 7727,
        paymentMethod: "credit", purchaseDate: d(-70), paymentDueDate: null, paidDate: d(-70),
        status: "paid", memo: "", documentId: null, createdAt: ts(-70), updatedAt: ts(-70),
      },
      {
        id: "c38", projectId: "p6", type: "expense", vendorName: "エコ産業",
        title: "残材処分費", category: "disposal",
        amount: 25000, taxType: "inclusive", taxAmount: 2273,
        paymentMethod: "cash", purchaseDate: d(-66), paymentDueDate: null, paidDate: d(-66),
        status: "paid", memo: "", documentId: null, createdAt: ts(-66), updatedAt: ts(-66),
      },
      {
        id: "c39", projectId: "p6", type: "expense", vendorName: "タイムズ阿佐谷",
        title: "駐車場代", category: "parking",
        amount: 5000, taxType: "inclusive", taxAmount: 455,
        paymentMethod: "cash", purchaseDate: d(-67), paymentDueDate: null, paidDate: d(-67),
        status: "paid", memo: "", documentId: null, createdAt: ts(-67), updatedAt: ts(-67),
      },

      // ---------- p7: H様邸 クロス張替え（原価 205,000）----------
      {
        id: "c40", projectId: "p7", type: "material", vendorName: "サンゲツ",
        title: "クロス材", category: null,
        amount: 98000, taxType: "inclusive", taxAmount: 8909,
        paymentMethod: "credit", purchaseDate: d(-128), paymentDueDate: null, paidDate: d(-128),
        status: "paid", memo: "", documentId: null, createdAt: ts(-128), updatedAt: ts(-128),
      },
      {
        id: "c41", projectId: "p7", type: "order", vendorName: "内装工房ナカムラ",
        title: "クロス施工応援（2人工）", category: null,
        amount: 70000, taxType: "inclusive", taxAmount: 6364,
        paymentMethod: "transfer", purchaseDate: d(-125), paymentDueDate: d(-95), paidDate: d(-95),
        status: "paid", memo: "", documentId: null, createdAt: ts(-125), updatedAt: ts(-95),
      },
      {
        id: "c42", projectId: "p7", type: "expense", vendorName: "コーナンPRO 中野店",
        title: "パテ・副資材", category: "consumables",
        amount: 12000, taxType: "inclusive", taxAmount: 1091,
        paymentMethod: "cash", purchaseDate: d(-127), paymentDueDate: null, paidDate: d(-127),
        status: "paid", memo: "", documentId: null, createdAt: ts(-127), updatedAt: ts(-127),
      },
      {
        id: "c43", projectId: "p7", type: "expense", vendorName: "ENEOS",
        title: "ガソリン代", category: "fuel",
        amount: 8000, taxType: "inclusive", taxAmount: 727,
        paymentMethod: "credit", purchaseDate: d(-124), paymentDueDate: null, paidDate: d(-124),
        status: "paid", memo: "", documentId: null, createdAt: ts(-124), updatedAt: ts(-124),
      },
      {
        id: "c44", projectId: "p7", type: "expense", vendorName: "エコ産業",
        title: "残材処分費", category: "disposal",
        amount: 17000, taxType: "inclusive", taxAmount: 1545,
        paymentMethod: "cash", purchaseDate: d(-121), paymentDueDate: null, paidDate: d(-121),
        status: "paid", memo: "", documentId: null, createdAt: ts(-121), updatedAt: ts(-121),
      },
    ],
    documents: [
      {
        id: "d1", projectId: "p1", uploadedBy: "鈴木 大輔", documentType: "receipt",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "コーナンPRO 練馬店", documentDate: d(-32), totalAmount: 68000, taxAmount: 6182,
        ocrText: "コーナンPRO 練馬店\n木材・下地材ほか 12点\n合計 ¥68,000（内税 ¥6,182）",
        ai: ocr({
          documentType: "receipt", vendorName: "コーナンPRO 練馬店", documentDate: d(-32),
          totalAmount: 68000, taxAmount: 6182, confidence: "high",
          items: [{ name: "構造用合板 12mm", amount: 24800 }, { name: "垂木・胴縁材", amount: 18400 }, { name: "石膏ボード", amount: 14200 }, { name: "ビス・金物", amount: 10600 }],
          paymentMethod: "cash",
        }),
        assignmentConfidence: "high", status: "registered",
        registeredTo: { kind: "cost", id: "c3" }, createdAt: ts(-32), updatedAt: ts(-32),
      },
      {
        id: "d2", projectId: "p1", uploadedBy: "佐藤 健一", documentType: "invoice",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "佐藤設備工業", documentDate: d(-12), totalAmount: 850000, taxAmount: 77273,
        ocrText: "請求書\n佐藤設備工業\nデモ工務店株式会社 御中\n水道・ガス配管工事一式\n合計 ¥850,000",
        ai: ocr({
          documentType: "invoice", vendorName: "佐藤設備工業", documentDate: d(-12),
          totalAmount: 850000, taxAmount: 77273, confidence: "high",
          items: [{ name: "水道・ガス配管工事一式", amount: 850000 }],
          addressee: "デモ工務店株式会社", registrationNumber: "T9876543210987",
        }),
        assignmentConfidence: "high", status: "registered",
        registeredTo: { kind: "cost", id: "c1" }, createdAt: ts(-12), updatedAt: ts(-10),
      },
      {
        id: "d3", projectId: "p3", uploadedBy: "鈴木 大輔", documentType: "receipt",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "エスケー化研 東京支店", documentDate: d(-1), totalAmount: 46200, taxAmount: 4200,
        ocrText: "エスケー化研 東京支店\n追加塗料（プレミアムシリコン）\n合計 ¥46,200",
        ai: ocr({
          documentType: "receipt", vendorName: "エスケー化研 東京支店", documentDate: d(-1),
          totalAmount: 46200, taxAmount: 4200, confidence: "high",
          items: [{ name: "プレミアムシリコン 15kg × 2", amount: 46200 }],
          paymentMethod: "transfer",
        }),
        assignmentConfidence: "high", status: "needs_review",
        registeredTo: null, createdAt: ts(-1), updatedAt: ts(-1),
      },
      {
        id: "d4", projectId: null, uploadedBy: "鈴木 大輔", documentType: "receipt",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "ENEOS セルフ池袋SS", documentDate: d(0), totalAmount: 8900, taxAmount: 809,
        ocrText: "ENEOS セルフ池袋SS\nレギュラー 52.3L\n合計 ¥8,900",
        ai: ocr({
          documentType: "receipt", vendorName: "ENEOS セルフ池袋SS", documentDate: d(0),
          totalAmount: 8900, taxAmount: 809, confidence: "medium",
          items: [{ name: "レギュラーガソリン 52.3L", amount: 8900 }],
          paymentMethod: "credit",
        }),
        assignmentConfidence: "low", status: "attention",
        registeredTo: null, createdAt: ts(0), updatedAt: ts(0),
      },
      {
        id: "d5", projectId: "p2", uploadedBy: "佐藤 健一", documentType: "invoice",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "内装工房ナカムラ", documentDate: d(-3), totalAmount: 700000, taxAmount: 63636,
        ocrText: "御請求書\n内装工房ナカムラ\nデモ工務店株式会社 御中\nクロス・床仕上げ工事（高田馬場店舗）\n合計 ¥700,000",
        ai: ocr({
          documentType: "invoice", vendorName: "内装工房ナカムラ", documentDate: d(-3),
          totalAmount: 700000, taxAmount: 63636, confidence: "high",
          items: [{ name: "クロス仕上げ工事", amount: 420000 }, { name: "床仕上げ工事", amount: 280000 }],
          addressee: "デモ工務店株式会社", registrationNumber: "T5678901234567",
        }),
        assignmentConfidence: "high", status: "needs_review",
        registeredTo: null, createdAt: ts(-3), updatedAt: ts(-3),
      },
      {
        id: "d6", projectId: "p8", uploadedBy: "山田 太郎", documentType: "estimate",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "デモ工務店株式会社（自社控え）", documentDate: d(-5), totalAmount: 1850200, taxAmount: 168200,
        ocrText: "御見積書\n五十嵐 純 様\n浴室リフォーム工事一式\n合計 ¥1,850,200",
        ai: ocr({
          documentType: "estimate", vendorName: "デモ工務店株式会社", documentDate: d(-5),
          totalAmount: 1850200, taxAmount: 168200, confidence: "high",
          addressee: "五十嵐 純",
        }),
        assignmentConfidence: "high", status: "analyzed",
        registeredTo: null, createdAt: ts(-5), updatedAt: ts(-5),
      },
      {
        id: "d7", projectId: "p3", uploadedBy: "鈴木 大輔", documentType: "receipt_official",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "首都高速道路", documentDate: d(-2), totalAmount: 3200, taxAmount: 291,
        ocrText: "ETC利用証明書\n首都高速道路\n合計 ¥3,200",
        ai: ocr({
          documentType: "receipt_official", vendorName: "首都高速道路", documentDate: d(-2),
          totalAmount: 3200, taxAmount: 291, confidence: "high",
          paymentMethod: "credit",
        }),
        assignmentConfidence: "medium", status: "registered",
        registeredTo: { kind: "cost", id: "c19" }, createdAt: ts(-2), updatedAt: ts(-2),
      },
      {
        id: "d8", projectId: "p2", uploadedBy: "田中 美咲", documentType: "invoice",
        fileUrl: null, thumbnailUrl: null,
        vendorName: "", documentDate: null, totalAmount: null, taxAmount: null,
        ocrText: "", ai: null,
        assignmentConfidence: null, status: "pending",
        registeredTo: null, createdAt: ts(0), updatedAt: ts(0),
      },
    ],
    estimates: [
      {
        id: "e1", projectId: "p1", estimateNumber: "EST-0001",
        customerName: "阿部 誠", title: "キッチンリフォーム工事 御見積",
        items: [
          { id: "e1-1", name: "システムキッチン本体・施工", quantity: 1, unit: "式", unitPrice: 1800000, amount: 1800000 },
          { id: "e1-2", name: "給排水・ガス・電気工事", quantity: 1, unit: "式", unitPrice: 500000, amount: 500000 },
          { id: "e1-3", name: "内装補修工事", quantity: 1, unit: "式", unitPrice: 245000, amount: 245000 },
        ],
        subtotal: 2545000, taxAmount: 254500, total: 2799500,
        issueDate: d(-48), validUntil: d(-18), status: "accepted", memo: "",
        createdAt: ts(-48), updatedAt: ts(-45),
      },
      {
        id: "e2", projectId: "p8", estimateNumber: "EST-0002",
        customerName: "五十嵐 純", title: "浴室リフォーム工事 御見積",
        items: [
          { id: "e2-1", name: "ユニットバス本体（1616サイズ）", quantity: 1, unit: "式", unitPrice: 980000, amount: 980000 },
          { id: "e2-2", name: "解体・設備・電気工事", quantity: 1, unit: "式", unitPrice: 450000, amount: 450000 },
          { id: "e2-3", name: "内装仕上げ工事", quantity: 1, unit: "式", unitPrice: 252000, amount: 252000 },
        ],
        subtotal: 1682000, taxAmount: 168200, total: 1850200,
        issueDate: d(-5), validUntil: d(25), status: "sent", memo: "ご返答待ち",
        createdAt: ts(-5), updatedAt: ts(-5),
      },
      {
        id: "e3", projectId: "p5", estimateNumber: "EST-0003",
        customerName: "株式会社エムズプランニング", title: "追加造作工事 御見積",
        items: [
          { id: "e3-1", name: "追加間仕切り造作工事", quantity: 1, unit: "式", unitPrice: 380000, amount: 380000 },
          { id: "e3-2", name: "電源増設工事", quantity: 4, unit: "箇所", unitPrice: 15000, amount: 60000 },
        ],
        subtotal: 440000, taxAmount: 44000, total: 484000,
        issueDate: d(0), validUntil: d(30), status: "draft", memo: "原価超過分の回収のため早急に提出",
        createdAt: ts(0), updatedAt: ts(0),
      },
      {
        id: "e4", projectId: "p9", estimateNumber: "EST-0004",
        customerName: "株式会社イワタ物流", title: "倉庫改修工事 御見積",
        items: [
          { id: "e4-1", name: "倉庫内装改修工事一式", quantity: 1, unit: "式", unitPrice: 2450000, amount: 2450000 },
          { id: "e4-2", name: "電気設備更新工事", quantity: 1, unit: "式", unitPrice: 830000, amount: 830000 },
        ],
        subtotal: 3280000, taxAmount: 328000, total: 3608000,
        issueDate: d(-40), validUntil: d(-10), status: "lost", memo: "価格面で他社に決定",
        createdAt: ts(-40), updatedAt: ts(-15),
      },
    ],
    invoices: [
      {
        id: "i1", projectId: "p1", invoiceNumber: "INV-0001",
        customerName: "阿部 誠", title: "キッチンリフォーム工事 着手金",
        items: [
          { id: "i1-1", name: "キッチンリフォーム工事 着手金", quantity: 1, unit: "式", unitPrice: 1363636, amount: 1363636 },
        ],
        subtotal: 1363636, taxAmount: 136364, total: 1500000,
        invoiceDate: d(-40), dueDate: d(-25), paidDate: d(-35), status: "paid", memo: "",
        createdAt: ts(-40), updatedAt: ts(-35),
      },
      {
        id: "i2", projectId: "p1", invoiceNumber: "INV-0002",
        customerName: "阿部 誠", title: "キッチンリフォーム工事 完工金",
        items: [
          { id: "i2-1", name: "キッチンリフォーム工事 完工金", quantity: 1, unit: "式", unitPrice: 1181818, amount: 1181818 },
        ],
        subtotal: 1181818, taxAmount: 118182, total: 1300000,
        invoiceDate: d(-3), dueDate: d(25), paidDate: null, status: "sent", memo: "追加コンロ変更分を含む",
        createdAt: ts(-3), updatedAt: ts(-3),
      },
      {
        id: "i3", projectId: "p4", invoiceNumber: "INV-0003",
        customerName: "出口 幸子", title: "給湯器交換工事代金",
        items: [
          { id: "i3-1", name: "給湯器交換工事一式", quantity: 1, unit: "式", unitPrice: 345455, amount: 345455 },
        ],
        subtotal: 345455, taxAmount: 34545, total: 380000,
        invoiceDate: d(-9), dueDate: d(-2), paidDate: null, status: "sent", memo: "期限超過。要フォロー",
        createdAt: ts(-9), updatedAt: ts(-2),
      },
      {
        id: "i4", projectId: "p2", invoiceNumber: "INV-0004",
        customerName: "株式会社ベルフーズ", title: "原状回復工事代金",
        items: [
          { id: "i4-1", name: "原状回復工事一式", quantity: 1, unit: "式", unitPrice: 1500000, amount: 1500000 },
        ],
        subtotal: 1500000, taxAmount: 150000, total: 1650000,
        invoiceDate: null, dueDate: null, paidDate: null, status: "draft", memo: "発行前",
        createdAt: ts(-1), updatedAt: ts(-1),
      },
    ],
  };
  return db;
}
